### ISSUE TITLE
Do you have some examples of inference usecase?

### ISSUE THREAD

**Issue by msesboue** [KGConf/BookClub-Designing-BuildingEnterpriseKG#2]
chap 1, page 10, section 1.2.2, first paragraph, you mention the inference capability. Do you have some examples of inference used in practice? (beyond the hierarchical inference, e.g., subclass of, or broader/narrower)

**Comment by xeniacs** [comment]
Relative to this question, McGuinness' "Configuration" (Chapter 12, [The Description Logic Handbook](https://www.researchgate.net/publication/230745455_The_Description_Logic_Handbook_Theory_Implementation_and_Applications)) was the first application of inference I learnt about. It's about configuration of hardware parts, in order to satisfy the requirements of a customer's order.
But this was some 15 years ago. Are DL-based configuration systems used nowadays?
